/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Funciones.*;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import java.sql.SQLException;

/**
 *
 * @author yael
 */
public class Login extends javax.swing.JFrame {
    private static String numeroTarjetaLogueada;
     public Login() {
        initComponents();
    }
     
    public static String getNumeroTarjetaLogueada() {
        return numeroTarjetaLogueada;
    }


    private void setNumeroTarjetaLogueada(String numeroTarjeta) {
        numeroTarjetaLogueada = numeroTarjeta;
    }

private void iniciarSesion() {
    String numeroTarjeta = txtTarjeta.getText();  // Obtenemos el número de tarjeta desde el campo de texto

    if (numeroTarjeta != null && !numeroTarjeta.trim().isEmpty()) {
        setNumeroTarjetaLogueada(numeroTarjeta);  // Asignamos el número de tarjeta a la variable estática
        System.out.println("Número de tarjeta logueada: " + numeroTarjeta);  // Depuración
        // Continuar con la lógica del inicio de sesión
    } else {
        JOptionPane.showMessageDialog(this, "Número de tarjeta inválido.", "Error", JOptionPane.ERROR_MESSAGE);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtTarjeta = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        txtClave = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-230, 20, 630, 300));

        txtTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTarjetaActionPerformed(evt);
            }
        });
        jPanel2.add(txtTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 190, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ingrese la clave");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 190, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Numero de tarjeta");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, -1, -1));

        jButton3.setBackground(new java.awt.Color(204, 204, 0));
        jButton3.setText("Aceptar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, -1, -1));
        jPanel2.add(txtClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 392, 190, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 510, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 882, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTarjetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTarjetaActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Verificar si los campos están vacíos
        if (txtTarjeta.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar el número de tarjeta", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (txtClave.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar la clave", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Validar que txtTarjeta contiene solo números y tiene exactamente 16 dígitos
        String numeroTarjeta = txtTarjeta.getText();
        if (!numeroTarjeta.matches("\\d{16}")) {
            JOptionPane.showMessageDialog(this, "El número de tarjeta debe contener exactamente 16 dígitos numéricos", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validar que txtClave contiene solo números y tiene exactamente 4 dígitos
        String claveTarjeta = new String(((javax.swing.JPasswordField) txtClave).getPassword());
        if (!claveTarjeta.matches("\\d{4}")) {
            JOptionPane.showMessageDialog(this, "La clave debe contener exactamente 4 dígitos numéricos", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Crear una instancia de clsBD_Conexion y ControladorLogin
        clsBD_Conexion conexion = new clsBD_Conexion();
        ControladorLogin controladorLogin = new ControladorLogin(conexion);

        try {
            // Conectar a la base de datos
            conexion.conectarBD();

            // Validar las credenciales
            if (controladorLogin.validarLogin(numeroTarjeta, claveTarjeta)) {
                // Configurar la tarjeta logueada
                setNumeroTarjetaLogueada(numeroTarjeta);
                System.out.println("Número de tarjeta logueada: " + numeroTarjeta); // Depuración

                // Obtener los datos del usuario
                String[] datosUsuario = controladorLogin.obtenerDatosUsuario(numeroTarjeta);
                if (datosUsuario != null) {
                    // Verificar si el arreglo tiene los datos correctos
                    String tipoUsuario = (datosUsuario.length > 2) ? datosUsuario[2] : "ADMINISTRADOR";  // Asume ADMINISTRADOR si no tiene saldo

                    if (tipoUsuario.equalsIgnoreCase("ADMINISTRADOR")) {
                        // Redirigir a la interfaz del Administrador
                        Registro registro = new Registro(datosUsuario[0]); // Nombre del usuario
                        registro.setVisible(true);
                    } else if (tipoUsuario.equalsIgnoreCase("CLIENTE")) {
                        // Redirigir a la interfaz del Cliente
                        MenuModificado menu = new MenuModificado(datosUsuario[0], datosUsuario[1], numeroTarjeta);
                        menu.setVisible(true);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Error al obtener datos del usuario", "Error", JOptionPane.ERROR_MESSAGE);
                }

                this.dispose(); // Cerrar la ventana actual
            } else {
                JOptionPane.showMessageDialog(this, "Número de tarjeta o clave incorrectos.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error de conexión con la base de datos: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField txtClave;
    private javax.swing.JTextField txtTarjeta;
    // End of variables declaration//GEN-END:variables
}
