/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package VistaCajero;

import Funciones.clsBD_Conexion;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author yael
 */
public class Tarjetas extends javax.swing.JPanel {
private DefaultTableModel modeloTabla; // Modelo de tabla
    /**
     * Creates new form Tarjetas
     */
    public Tarjetas() {
        initComponents();
         modeloTabla = new DefaultTableModel(new String[]{"ID Tarjeta", "Número de Tarjeta", "Clave"}, 0);
        tblTarjeta.setModel(modeloTabla); 
        cargarTarjetas();
    }
    
private void cargarTarjetas() {
        // Limpiar el modelo antes de cargar nuevos datos
        modeloTabla.setRowCount(0);

        // Conexión a la base de datos
        clsBD_Conexion conexion = new clsBD_Conexion();
        try {
            conexion.conectarBD(); // Conexión a la BD

            // Consulta SQL para obtener tarjetas solo vinculadas a clientes
            String query = "SELECT t.idtarjeta, t.numero_tarjeta, t.clave_tarjeta " +
                           "FROM tarjeta t " +
                           "WHERE t.idtarjeta IN (SELECT tarjeta_id FROM cliente WHERE tarjeta_id IS NOT NULL)";
            PreparedStatement pst = conexion.getConexion().prepareStatement(query);
            ResultSet rs = pst.executeQuery();

            // Recorrer los resultados y agregarlos al modelo
            while (rs.next()) {
                int idTarjeta = rs.getInt("idtarjeta");
                String numeroTarjeta = rs.getString("numero_tarjeta");
                int claveTarjeta = rs.getInt("clave_tarjeta");

                // Agregar fila al modelo
                modeloTabla.addRow(new Object[]{idTarjeta, numeroTarjeta, claveTarjeta});
            }

            // Cerrar recursos
            rs.close();
            pst.close();
            conexion.desconectarBD();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al cargar tarjetas: " + e.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTarjeta = new javax.swing.JTable();
        label = new javax.swing.JLabel();

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Tarjetas de clientes");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, -1, -1));

        tblTarjeta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "id_tarjeta", "NumeroDeTarjeta ", "Cliente", "Saldo", "Nip"
            }
        ));
        jScrollPane1.setViewportView(tblTarjeta);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 550, 220));
        jPanel2.add(label, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, 170, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label;
    private javax.swing.JTable tblTarjeta;
    // End of variables declaration//GEN-END:variables
}
